project_id: '804778'
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /i18n/locales/en.json
    translation: /i18n/locales/%locale_with_underscore%.json
pull_request_title: 'chore: update translations'
