project_id: '804778'
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /i18n/locales/en.json
    translation: /i18n/locales/%two_letters_code%.json
    excluded_target_languages:
      - en