FROM node:22-alpine AS deps

WORKDIR /opt/5stack

COPY package.json yarn.lock .yarnrc.yml ./

RUN corepack enable && corepack prepare 

RUN yarn install --immutable

FROM node:22-alpine

WORKDIR /opt/5stack

COPY package.json yarn.lock .yarnrc.yml ./

RUN corepack enable && corepack prepare

COPY --from=deps /opt/5stack/node_modules ./node_modules
COPY . .

ENV HOST=0.0.0.0
EXPOSE 3000

CMD [ "yarn", "dev" ]