import {
  Puzzle,
  Package,
  Boxes,
  Box,
  ShoppingBag,
  ShoppingCart,
  Store,
  Swords,
  Sword,
  Shield,
  ShieldHalf,
  Target,
  Crosshair,
  Gamepad2,
  Sparkles,
  Star,
  Trophy,
  Medal,
  Crown,
  Flame,
  Zap,
  Rocket,
  Wrench,
  Hammer,
  Cog,
  Settings,
  LayoutGrid,
  LayoutDashboard,
  AppWindow,
  Globe,
  Map,
  MapPin,
  Compass,
  Users,
  User,
  Bot,
  Shirt,
  Palette,
  Brush,
  Image,
  Camera,
  Video,
  Film,
  Music,
  Headphones,
  Radio,
  Newspaper,
  BookOpen,
  FileText,
  Calendar,
  Clock,
  Bell,
  MessageSquare,
  Heart,
  Coins,
  DollarSign,
  CreditCard,
  Gift,
  Tag,
  Ticket,
  Flag,
  Bookmark,
  Home,
  Building,
  Server,
  Database,
  Terminal,
  Code,
  Cpu,
  Activity,
  BarChart,
  List,
  Folder,
  Link,
} from "lucide-vue-next";
import type { Component } from "vue";

// Curated, offline icon set for plugins. The picker searches these names;
// anything unrecognised falls back to Puzzle. Kept explicit (rather than
// lucide's full ~1.5k-icon set) so the bundle stays small.
export const PLUGIN_ICONS: Record<string, Component> = {
  puzzle: Puzzle,
  package: Package,
  boxes: Boxes,
  box: Box,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  store: Store,
  swords: Swords,
  sword: Sword,
  shield: Shield,
  "shield-half": ShieldHalf,
  target: Target,
  crosshair: Crosshair,
  gamepad: Gamepad2,
  sparkles: Sparkles,
  star: Star,
  trophy: Trophy,
  medal: Medal,
  crown: Crown,
  flame: Flame,
  zap: Zap,
  rocket: Rocket,
  wrench: Wrench,
  hammer: Hammer,
  cog: Cog,
  settings: Settings,
  "layout-grid": LayoutGrid,
  dashboard: LayoutDashboard,
  "app-window": AppWindow,
  globe: Globe,
  map: Map,
  "map-pin": MapPin,
  compass: Compass,
  users: Users,
  user: User,
  bot: Bot,
  shirt: Shirt,
  palette: Palette,
  brush: Brush,
  image: Image,
  camera: Camera,
  video: Video,
  film: Film,
  music: Music,
  headphones: Headphones,
  radio: Radio,
  newspaper: Newspaper,
  book: BookOpen,
  file: FileText,
  calendar: Calendar,
  clock: Clock,
  bell: Bell,
  message: MessageSquare,
  heart: Heart,
  coins: Coins,
  dollar: DollarSign,
  "credit-card": CreditCard,
  gift: Gift,
  tag: Tag,
  ticket: Ticket,
  flag: Flag,
  bookmark: Bookmark,
  home: Home,
  building: Building,
  server: Server,
  database: Database,
  terminal: Terminal,
  code: Code,
  cpu: Cpu,
  activity: Activity,
  chart: BarChart,
  list: List,
  folder: Folder,
  link: Link,
};

export const PLUGIN_ICON_NAMES = Object.keys(PLUGIN_ICONS);

export const DEFAULT_PLUGIN_ICON = Puzzle;
