#!/bin/bash
# Post-processes the graphql-zeus codegen output. Runs from the `codegen` npm script, right
# after `zeus <url> ./generated --ts --td`.
#
#   1. typedDocumentNode.ts -- value imports for type-only exports, which breaks Vite.
#   2. index.ts             -- serialize Date before ResolveFromPath is consulted (see below).
#   3. const.ts             -- staged as const.full.ts, then slimmed to what Zeus can still
#                              answer with, and the reduction is proven before it is accepted.
#
# Order matters: the slim map must never be on disk without the Date patch alongside it.
set -euo pipefail
cd "$(dirname "$0")/.."

if [[ "$OSTYPE" == "darwin"* ]]; then SED_INPLACE=(sed -i ""); else SED_INPLACE=(sed -i); fi

# --- 1. type-only imports -------------------------------------------------------------------
"${SED_INPLACE[@]}" \
  -e "s/import { TypedDocumentNode }/import type { TypedDocumentNode }/" \
  -e "s/  ValueTypes,/  type ValueTypes,/" \
  -e "s/  GenericOperation,/  type GenericOperation,/" \
  -e "s/  OperationOptions,/  type OperationOptions,/" \
  -e "s/  GraphQLTypes,/  type GraphQLTypes,/" \
  -e "s/  InputType,/  type InputType,/" \
  -e "s/  ScalarDefinition,/  type ScalarDefinition,/" \
  -e "s/  ThunderGraphQLOptions,/  type ThunderGraphQLOptions,/" \
  -e "s/  ExtractVariables,/  type ExtractVariables,/" \
  ./generated/zeus/typedDocumentNode.ts

# --- 2. Date handling in InternalArgsBuilt.arb ----------------------------------------------
# The slim map answers 'not' for most custom-scalar paths, and the 'not' fallthrough treats a
# Date as a plain object -- Object.entries(new Date()) is [] -- so a Date argument would
# silently serialize as `{}`. JSON.stringify goes through Date.toJSON, which is exactly what
# the full map's scalar branch did, so this is behaviour-preserving and map-independent.
# It also fixes the same latent bug for Dates at paths the full map never resolved either.
if ! grep -q "a instanceof Date" ./generated/zeus/index.ts; then
  node - <<'NODE'
const fs = require("fs");
const F = "./generated/zeus/index.ts";
const anchor = "    const checkType = ResolveFromPath(props, returns, ops)(p);";
const patch = `    // Serialize Date before consulting the schema map: the 'not' fallthrough would treat it
    // as a plain object and emit {} (see scripts/patch-zeus-codegen.sh).
    if (a instanceof Date) {
      return JSON.stringify(a);
    }
`;
const src = fs.readFileSync(F, "utf8");
if (!src.includes(anchor)) { console.error("patch-zeus-codegen: arb() anchor not found in index.ts"); process.exit(1); }
fs.writeFileSync(F, src.replace(anchor, patch + anchor));
console.log("patch-zeus-codegen: Date handling added to arb()");
NODE
fi

# --- 3. slim the schema map, and prove it ---------------------------------------------------
# This step opens by moving const.ts aside as the full map, which is only correct when `zeus`
# has just written a fresh full one. Invoked standalone it would move the ALREADY SLIMMED map
# over const.full.ts and then slim that -- destroying the only copy of the full map. The
# verifier does catch the result ("refusing to verify a map against itself") and exits 1, but
# by then const.full.ts is gone and only a codegen brings it back. Refuse while it is cheap.
if grep -q "GENERATED by scripts/slim-zeus-const.mjs" ./generated/zeus/const.ts; then
  echo "patch-zeus-codegen: generated/zeus/const.ts is already the slimmed map." >&2
  echo "  This script must run immediately after \`zeus\`, which writes a fresh full const.ts." >&2
  echo "  Run \`yarn codegen\` rather than invoking this script on its own." >&2
  exit 1
fi

mv ./generated/zeus/const.ts ./generated/zeus/const.full.ts
node ./scripts/slim-zeus-const.mjs
node ./scripts/verify-zeus-map.mjs
